### ISSUE TITLE
[Research] Check prices for the routing of PCBs

### ISSUE THREAD

**Issue by Slyde-R** [CyberducksTeam/HACKberry#2]
### Description

Check the cost of the PCB(s) by using the gerber files from the repository and a vendor that ships to Austria. Include the cost of parts that have to be bought separately etc. Add the price and part list to a sheet located in [this ](https://drive.google.com/drive/folders/1K-2nTi3Mq7XBdJcHd77PQMIqDGN6I6P-?usp=drive_link) folder.

### Solution Path

Boards:
- [x] MK1 or MK2? 
- [x] MK1
- [x] Battery Board
- [x] Sensor Board

**Comment by Slyde-R** [comment]
![Image](https://github.com/CyberducksTeam/HACKberry/assets/93402232/b52ad314-92cb-4404-bfb2-d27d3ababa7b)

Mk2 costs 79€ including delivery - from Hackberry

**Comment by Slyde-R** [comment]
soldering the MK2 board is not feasable -> MK1 board with separate arduino

**Comment by Slyde-R** [comment]
![Image](https://github.com/CyberducksTeam/HACKberry/assets/93402232/c2d675a8-9bd8-4c7e-856a-925dc0884ebd)



![Image](https://github.com/CyberducksTeam/HACKberry/assets/93402232/e313b0c4-e247-4219-8d6d-5dde4bb7075e)


5 of each board (hand, hand_left, sensor, battery) for a total of

**Comment by Slyde-R** [comment]
TODO: check footprint and pin out of audio jacks (highlighted in BOM)

**Comment by weberLeon** [comment]
@Slyde-R 

- If we opt for a 4-pin connector, the ArduinoMicroShieldBoard01 PCB will have to be adapted. This shouldn't be a problem as there is more than enough space as you can see in the screenshot.  
![Image](https://github.com/CyberducksTeam/HACKberry/assets/44413275/337d4426-aa75-4c4b-a193-8e7667019da8)

- The dimensions of the replacement headphone jack should be fairly similar, but may vary slightly as there is quite a lot of space in the design. (This should be checked again once a headphone jack has been selected and the PCB has been adapted).  
![Image](https://github.com/CyberducksTeam/HACKberry/assets/44413275/1a67d976-9609-4651-b279-1c404123f489)

- Furthermore, a different (4pin) audio cable needs to be selected in order to ensure compatibly with the used headphone jack. (already marked in red in BOM).

**Comment by Slyde-R** [comment]
edited PCB files to accomodate different 3pin jack exported files can be found [here](https://drive.google.com/drive/folders/1maboma9Yz2E8RrRPJgDyxDnrLxclWt5I?usp=drive_link).
The new subtotal is because of the lead free finish:


![Image](https://github.com/CyberducksTeam/HACKberry/assets/93402232/573cc68b-efb6-4e39-94f9-d3910f54dbf4)

This is with the most expensive and also quickest shipping as the slowest takes 14-16 business days and other slower ones only save 1.98EUR

**Comment by Slyde-R** [comment]
-> ready to order

**Comment by Slyde-R** [comment]
I ordeered the PCBs

[invoice.pdf](https://github.com/CyberducksTeam/HACKberry/files/13641230/invoice.pdf)
